apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-sensors-consumer-web-live
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: true
    app.kubernetes.io/part-of: spring-sensors-consumer-web-live-rabbit
    app: backstage
spec:
  source:
    git:
      url: https://github.com/arulvannala/spring-sensors-rabbit
      ref:
        branch: main
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "4"
  serviceClaims:
    - name: rmq
      ref:
        apiVersion: rabbitmq.com/v1beta1
        kind: RabbitmqCluster
        name: rmq-1
